services:

  web:
    # uses a modified version of: https://github.com/macbre/docker-nginx-http3
    image: ${NGINX_IMAGE}:${NGINX_VERSION}
    build:
      context: ./dockerfiles/nginx/
      args:
        NGINX_USER_UID: 33
        NGINX_GROUP_GID: 33

  app:
    image: nextcloud:${NEXTCLOUD_VERSION}
    build:
      dockerfile: ./dockerfiles/nextcloud/Dockerfile

