services:
  database:
    image: mariadb:${MARIADB_VERSION}
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    networks:
      - nextcloud
    volumes:
      - ${DATABASE_VOLUME_BASE_PATH}/volumes/database/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    restart: unless-stopped

  redis:
    image: redis:${REDIS_VERSION}
    networks:
      - nextcloud
    restart: unless-stopped

  web:
    image: nginx:${NGINX_VERSION}
    networks:
      - nextcloud
    ports:
      - 80:80
    volumes:
      - ${NEXTCLOUD_VOLUME_BASE_PATH}/volumes/nextcloud:/var/www/html:z
      - ${NGINX_VOLUME_BASE_PATH}/volumes/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      UID: 33 # default www-data for Ubuntu that will be hosting the files
      GID: 33 # default www-data for Ubuntu that will be hosting the files
    entrypoint:
      - /bin/sh
      - -c
      - |
        usermod -a -G www-data nginx
        /docker-entrypoint.sh nginx -g 'daemon off;'
    restart: unless-stopped

  app:
    image: nextcloud:${NEXTCLOUD_VERSION}
    build:
      dockerfile: /usr/docker/nextcloud/dockerfiles/nextcloud/Dockerfile
    depends_on:
      - database
      - redis
    networks:
      - nextcloud
    volumes:
      - ${NEXTCLOUD_VOLUME_BASE_PATH}/volumes/nextcloud:/var/www/html:z
      - ${PHP_VOLUME_BASE_PATH}/volumes/php/php-fpm-www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_HOST
      - REDIS_HOST
      - OVERWRITEHOST
      - APACHE_DISABLE_REWRITE_IP
      - NEXTCLOUD_ADMIN_USER
      - NEXTCLOUD_ADMIN_PASSWORD
    restart: unless-stopped

  cron:
    image: nextcloud:${NEXTCLOUD_VERSION}
    depends_on:
      - database
      - redis
    networks:
      - nextcloud
    volumes:
      - ${NEXTCLOUD_VOLUME_BASE_PATH}/volumes/nextcloud:/var/www/html:z
      - ${PHP_VOLUME_BASE_PATH}/volumes/php/php-fpm-www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    entrypoint: /cron.sh
    restart: unless-stopped

networks:
  nextcloud:
